"use client";

import { motion } from "framer-motion";

interface Props {
  explanations: Record<string, number>;
}

export default function SHAPInsightDeck({ explanations }: Props) {
  const entries = Object.entries(explanations || {})
    .sort((a, b) => b[1] - a[1])
    .slice(0, 16);

  if (entries.length === 0) {
    return (
      <div className="text-zinc-500 font-light text-sm">
        No SHAP impact vectors generated by the engine.
      </div>
    );
  }

  const container = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: {
        staggerChildren: 0.04,
      },
    },
  };

  const item = {
    hidden: { opacity: 0, scale: 0.9 },
    show: { opacity: 1, scale: 1 },
  };

  return (
    <motion.div
      variants={container}
      initial="hidden"
      animate="show"
      className="flex flex-wrap gap-3"
    >
      {entries.map(([skill, weight], idx) => {
        const isPositive = weight > 0;
        return (
          <motion.div
            key={idx}
            variants={item}
            className="group relative cursor-default"
          >
            <div
              className={`px-4 py-2 rounded-full border border-white/5 bg-white/5 backdrop-blur-xl text-sm transition-all duration-300 ${isPositive ? "hover:border-emerald-500/30 hover:bg-emerald-500/10 text-zinc-300 hover:text-emerald-100 shadow-[0_0_15px_rgba(16,185,129,0)] hover:shadow-[0_0_15px_rgba(16,185,129,0.1)]" : "hover:border-red-500/30 hover:bg-red-500/10 text-zinc-400 hover:text-red-100 shadow-[0_0_15px_rgba(248,113,113,0)] hover:shadow-[0_0_15px_rgba(248,113,113,0.1)]"}`}
            >
              {skill}
            </div>
            {/* Elegant Tooltip overlay */}
            <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-3 w-52 p-4 bg-zinc-900/90 backdrop-blur-2xl border border-white/10 rounded-2xl shadow-2xl opacity-0 scale-95 pointer-events-none group-hover:opacity-100 group-hover:scale-100 transition-all duration-300 z-10">
              <div className="text-[10px] font-medium text-zinc-500 mb-1 uppercase tracking-widest">
                SHAP Weighting
              </div>
              <div
                className={`text-sm font-medium ${isPositive ? "text-emerald-400" : "text-red-400"}`}
              >
                {isPositive ? "+" : ""}
                {weight.toFixed(2)}% Impact
              </div>
              <div className="text-xs text-zinc-400 mt-2 font-light leading-relaxed">
                {isPositive
                  ? "This terminology matched heavily against localized semantic clusters in the JD."
                  : "Low semantic similarity detected. The engine penalized this missing trait."}
              </div>
            </div>
          </motion.div>
        );
      })}
    </motion.div>
  );
}
